# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HN Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HN Client
  
  # For develop releases:
#   pod 'HNFoundation', :git => "git@github.com:prof18/hn-foundation-cocoa-xcframework.git", :branch => 'develop'
  
  # For stable releases
  pod 'HNFoundation', :git => "git@github.com:prof18/hn-foundation-cocoa-xcframework.git", :tag => '2.0.0'
  
  pod 'Alamofire', '~> 5.2'
  

end
